### ISSUE TITLE
A new version?

### ISSUE THREAD

**Issue by Mange** [kiwigrid/gcloud-kubectl-helm#24]
I need Helm 3.5 and I see that no tag has been pushed for almost half a year now. Would it be possible to get an update image out?

**Comment by monotek** [comment]
As far as i konow kiwigrid is not using this image anymore, so that's the reason it's not updated.
Maybe the repo should be set to "archived" so users know they have to fork it to use it.

I've created a similar image with helm 3.5, to use it in gitlab ci: https://github.com/Bike24/ci-tools
But as we're moving away from gitlab now it might be abondoned too.

**Comment by Mange** [comment]
Thanks!
